Update CKB Bitcoin SPV Type Lock.md
ckb-cell/ckb-bitcoin-spv-contracts pull request #28
Opened 2024-06-07 07:51 UTC by KryStar11

Refinements to the CKB Bitcoin SPV Type Lock Documentation.

2024-06-10 15:00 UTC, EthanYuan commented on contracts/ckb-bitcoin-spv-type-lock/README.md
> +  consisting of one SPV client cell in the inputs and one SPV client cell in the outputs. This similarity can lead to ambiguity.
```suggestion
  consisting of one SPV client cell in the inputs and one SPV client cell in the outputs. However, this similarity can lead to ambiguity.
```

2024-06-10 15:12 UTC, EthanYuan commented on contracts/ckb-bitcoin-spv-type-lock/README.md
> +  introduced in [CKB RFC 0032], and `Data2` is introduced in [CKB RFC 0051].
```suggestion
  `Data1` is introduced in [CKB RFC 0032], and `Data2` is introduced in [CKB RFC 0051].
```

Duplicates the link:

> Don't set hash type[^1]

2024-06-10 15:21 UTC, EthanYuan commented on contracts/ckb-bitcoin-spv-type-lock/README.md
> +    - In cases where only one SPV client has failed, the reorg transaction must involve the reconstruction of one separate SPV clients;
```suggestion
    - In cases where only one SPV client has failed, the reorg transaction must involve the reconstruction of one additional  SPV client;
```

2024-06-10 15:21 UTC, EthanYuan commented on contracts/ckb-bitcoin-spv-type-lock/README.md
> +    - Specifically, the reorg transaction for one stale SPV client should include two SPV client cell in the `inputs` and two SPV client
```suggestion
    Specifically, the reorg transaction for one stale SPV client should include two SPV client cell in the `inputs` and two SPV client
```

2024-06-10 15:22 UTC, EthanYuan commented on contracts/ckb-bitcoin-spv-type-lock/README.md
> +    - Considering that reorgs are a rare occurrence on the Bitcoin mainnet, the cost incurred by this approach is considered manageable.
```suggestion
    Considering that reorgs are a rare occurrence on the Bitcoin mainnet, the cost incurred by this approach is considered manageable.
```

2024-06-11 02:05 UTC, EthanYuan submitted a review, later dismissed

2024-06-11 02:07 UTC, EthanYuan commented on contracts/ckb-bitcoin-spv-type-lock/README.md
>  # CKB Bitcoin SPV Type Lock
```suggestion
# CKB Bitcoin SPV Type Script
```

Suggest changing the filename as well

2024-06-12 05:47 UTC, Flouse commented on contracts/ckb-bitcoin-spv-type-lock/README.md
> +A Bitcoin  SPV on CKB consists of cells that are managed by the CKB Bitcoin SPV Type Lock and identified by the script args. The number of live cells with the script args remains fixed once created,
```suggestion
A Bitcoin  SPV on CKB consists of cells that are managed by the CKB Bitcoin SPV Type Script and identified by the script args. The number of live cells with the script args remains fixed once created, and these cells will be destroyed collectively as a group.
```

2024-06-12 05:47 UTC, Flouse commented on contracts/ckb-bitcoin-spv-type-lock/README.md
> +  The SPV info cell stores the basic information of the current Bitcoin SPV instance, such as `tip_ client_cell_id`. Each Bitcoin SPV
```suggestion
  The SPV info cell stores the basic information of the current Bitcoin SPV instance, such as `tip_client_id`. Each Bitcoin SPV
```

2024-06-12 06:01 UTC, Flouse requested changes

2024-06-12 06:01 UTC, Flouse commented on contracts/ckb-bitcoin-spv-type-lock/README.md
> +  The `outputs` include one SPV info cell and at least one SPV client cell. Cells should be consecutive, with the SPV info cell first,
```suggestion
  The `outputs` include one SPV info cell and at least three SPV client cell. Cells should be consecutive, with the SPV info cell first,
```

See https://github.com/KryStar11/ckb-bitcoin-spv-contracts/blob/770049914b6818f51b53c11be434a43876b87c45/contracts/ckb-bitcoin-spv-type-lock/src/operations/create.rs#L13-L39

2024-06-12 06:04 UTC, Flouse commented on contracts/ckb-bitcoin-spv-type-lock/README.md
> +    cell in the `outputs` ;
```suggestion
    cells in the `outputs` ;
```

2024-06-12 06:07 UTC, Flouse approved these changes

2024-06-12 06:08 UTC, merged